# Use a pipeline as a high-level helper
from transformers import pipeline

summarizer = pipeline("summarization", model="Falconsai/text_summarization")


def Summary(text):
    return summarizer(text, max_length=300, min_length=30, do_sample=False)


# text = "C programming language, developed by Dennis Ritchie at Bell Labs in the early 1970s, remains one of the most influential and widely used programming languages today. Its simplicity combined with powerful features has made it a popular choice for developing system software, application software, device drivers, and even modern operating systems like Unix and Linux. One of the key strengths of C is its ability to access low-level functionalities of the computer while still providing high-level abstractions, making it suitable for both system-level programming and application development. The syntax of C is concise and elegant, allowing programmers to express complex ideas with minimal code, which contributes to its efficiency and readability. C is also highly portable, meaning that programs written in C can run on a wide range of platforms with minimal modification. This portability has contributed to its widespread adoption across various domains.Understanding C programming involves grasping fundamental concepts such as variables, data types, operators, control structures (such as loops and conditionals), functions, arrays, pointers, and structures. Mastery of these concepts allows programmers to manipulate data efficiently, design algorithms effectively, and write robust and maintainable code. Moreover, C provides features for dynamic memory allocation, enabling programs to manage memory resources dynamically during runtime. However, this flexibility comes with the responsibility of managing memory carefully to prevent memory leaks and other runtime errors.In addition to its core features, C also supports a rich set of standard libraries that provide functions for tasks such as input/output operations, string manipulation, mathematical computations, and more. These libraries streamline the development process by offering pre-written functions that programmers can leverage to accomplish common tasks without reinventing the wheel. Overall, the combination of simplicity, power, portability, and extensive library support has solidified C's position as a cornerstone of modern programming and continues to attract developers seeking to build efficient and reliable software solutions."
# i want to only print the summary in normal format but Summary function return a json
# so i will print only the summary
# print(Summary(text)[0]['summary_text'])

# text = "C programming language, developed by Dennis Ritchie at Bell Labs in the early 1970s, remains one of the most influential and widely used programming languages today. Its simplicity combined with powerful features has made it a popular choice for developing system software, application software, device drivers, and even modern operating systems like Unix and Linux. One of the key strengths of C is its ability to access low-level functionalities of the computer while still providing high-level abstractions, making it suitable for both system-level programming and application development. The syntax of C is concise and elegant, allowing programmers to express complex ideas with minimal code, which contributes to its efficiency and readability. C is also highly portable, meaning that programs written in C can run on a wide range of platforms with minimal modification. This portability has contributed to its widespread adoption across various domains.Understanding C programming involves grasping fundamental concepts such as variables, data types, operators, control structures (such as loops and conditionals), functions, arrays, pointers, and structures. Mastery of these concepts allows programmers to manipulate data efficiently, design algorithms effectively, and write robust and maintainable code. Moreover, C provides features for dynamic memory allocation, enabling programs to manage memory resources dynamically during runtime. However, this flexibility comes with the responsibility of managing memory carefully to prevent memory leaks and other runtime errors.In addition to its core features, C also supports a rich set of standard libraries that provide functions for tasks such as input/output operations, string manipulation, mathematical computations, and more. These libraries streamline the development process by offering pre-written functions that programmers can leverage to accomplish common tasks without reinventing the wheel. Overall, the combination of simplicity, power, portability, and extensive library support has solidified C's position as a cornerstone of modern programming and continues to attract developers seeking to build efficient and reliable software solutions.i want to only print the summary in normal format but Summary function return a jsonso i will print only the summary"
# print(Summary(text)[0]['summary_text'])